### ISSUE TITLE
Errors on non-empty repos

### ISSUE THREAD

**Issue by milescrabill** [mozilla-services/elmo-automation#4]
I ran the `manage.py localrepos` on the webapp and kicked a10n off and saw this error - only once from what I can tell. Maybe they stepped on each others' toes?

```
2018-04-06 19:00:46,290 - Connected to amqp://<transport url>//
2018-04-06 19:00:46,307 - got hg-push message {u'repository_id': 78, u'type': u'hg-push', u'pushes': [{u'date': 1520340804, u'changesets': [u'24f636738262a838bfa487dc54076fbc2d483315'], u'user': u'pontoon@mozilla.com', u'id': 595}, {u'date': 1520340824, u'changesets': [u'678cb761651beedb6cdb9c200fd0e36e1ba92f45'], u'user': u'pontoon@mozilla.com', u'id': 596}]}
2018-04-06T19:00:47-0500 [HTTPPageGetter (TLSMemoryBIOProtocol),client] l10n-central/cs got 50 pushes
2018-04-06T19:00:48-0500 [HTTPPageGetter (TLSMemoryBIOProtocol),client] l10n-central/cy got 39 pushes
2018-04-06 19:00:48,640 - got hg-push message {u'repository_id': 2, u'type': u'hg-push', u'pushes': [{u'date': 1520341585, u'changesets': [u'894cbf4db50135cb80db34ec06b10b7e68429902'], u'user': u'mozilla@jorgk.com', u'id': 14162}]}
2018-04-06T19:00:49-0500 [HTTPPageGetter (TLSMemoryBIOProtocol),client] l10n-central/da got 26 pushes
2018-04-06 19:00:50,308 - handlePushes failed: 1
Traceback (most recent call last):
File "/app/a10n/a10n/hg_elmo/worker.py", line 44, in process_pushes
close_connection=True)
File "/app/a10n/a10n/hg_elmo/utils.py", line 111, in handlePushes
do_update=do_update)
File "/app/a10n/a10n/hg_elmo/utils.py", line 148, in _hg_repository_sync
hgrepo = hglib.clone(source=str(url), dest=str(repopath))
File "/app/env/lib/python2.7/site-packages/hglib/__init__.py", line 38, in clone
raise error.CommandError(args, proc.returncode, out, err)
CommandError: (255, '', "abort: destination '/data/repos/comm-central' is not empty")
```

**Comment by Pike** [comment]
We figured this out, there was an incomplete clone left-over from a previous attempt to populate the repos. Cleaning that out helped. Working on a fix.

**Comment by Pike** [comment]
I'll fix this together with more logging in[ bug 1453502](https://bugzilla.mozilla.org/show_bug.cgi?id=1453502).
